# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/100-numpy-exercises


'https://jovian.ml/aakashns/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.25.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.array([1,2,3,4,5])
print(len(arr))
print(arr.size*arr.itemsize)   # 5 * 4 bit

5
40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
# doc from cmd line
print(help(np.add))

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
arr = np.zeros(10,dtype=np.int8)
arr[5-1] = 1
print(arr)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
arr = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
arr = arr[::-1]
print(arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
arr = np.array([1,2,0,0,4,0])
print("indices of non zero elements in array")
for index,values in np.ndenumerate(arr):
    if values != 0:
        print(index[0],end=" ")


indices of non zero elements in array
0 1 4 

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

<IPython.core.display.Javascript object>

In [ ]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
print(np.eye(3,dtype = np.int8))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
arr = np.random.randint(1,100,size=(3,3,3))
print(arr)


[[[35  1  9]
  [ 2 89 46]
  [19 77 19]]

 [[37 57 36]
  [69 50 11]
  [74 27 25]]

 [[99 70 92]
  [95 75 86]
  [72 41 36]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
arr = np.random.randint(1,100,size=(10,10))
print(arr.max())
print(arr.min())

98
1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
arr = np.random.rand(30)
print(arr.mean())

0.3871322053905924


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
arr = np.zeros(3,dtype = np.int8)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [40]:
# roww = eval(input("enter no. of rows : "))
# coll = eval(input("enter no. of col : "))
# arr = np.zeros(shape=(roww,coll),dtype = np.int8)
# for index,value in np.ndenumerate(arr):
#     row = index[0]
#     col = index[1]
#     if row==0 or col==coll-1 or row==roww-1 or col==0:
#         arr[row,col] = 1

# print(arr)

arr2 = np.ones(shape=(5,5),dtype = np.int8)
print(arr2)
arr2 = np.pad(arr,pad_width=1, mode='constant', constant_values=0)
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [7]:
import numpy as np
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == (3 * 0.1))

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [8]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
arr = np.zeros(shape=(5,5),dtype=np.int8)
print(arr)
values = np.array([1,2,3,4])
np.fill_diagonal(arr[1:],values)
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [9]:
arr = np.zeros(shape=(4,4),dtype=np.int8)

for index,values in np.ndenumerate(arr):
    if (index[0]+index[1])%2==0:
        arr[index[0],index[1]] = 1

print(arr)



[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [1]:
import numpy as np
arr = np.ones(shape=(6,7,8))

for index,element in np.ndenumerate(arr):
  if (index[0]*index[1]*index[2])==100:
    print("100th elements is at index:- ",end="")
    print(index)
    break

100th elements is at index:- (4, 5, 5)


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [2]:
tile = np.array([[1,0],[0,1]])
#repeat four times horizontally and four times vertically
board = np.tile(tile,(4,4))
print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [4]:
x = arr = np.random.randint(1,100,size=(5,5))

from sklearn.preprocessing import normalize

# Normalizing rows of matrix axis = 1 and 0 for columnwise

x_normed = normalize(x, axis=1, norm='l1')
print(x_normed)

y = normalize(x, axis=0, norm='l1')
print(y)

[[0.51136364 0.08522727 0.19886364 0.1875     0.01704545]
 [0.30167598 0.09497207 0.17877095 0.16201117 0.26256983]
 [0.20901639 0.06967213 0.30327869 0.25409836 0.16393443]
 [0.04402516 0.11949686 0.3836478  0.39622642 0.05660377]
 [0.30990415 0.2428115  0.16613419 0.15974441 0.12140575]]
[[0.30100334 0.10416667 0.13779528 0.13924051 0.02189781]
 [0.18060201 0.11805556 0.12598425 0.12236287 0.34306569]
 [0.17056856 0.11805556 0.29133858 0.26160338 0.2919708 ]
 [0.02341137 0.13194444 0.24015748 0.26582278 0.06569343]
 [0.32441472 0.52777778 0.20472441 0.21097046 0.27737226]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [5]:
#defining custom datatype for rgba
#each color is tuple for rgba numbers
rgba_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

#creating array of colors
colors = np.array([
    (255, 0, 0, 255),     # Red with full opacity
    (0, 255, 0, 255),     # Green with full opacity
    (0, 0, 255, 255),     # Blue with full opacity
    (255, 255, 0, 128),    # Yellow with 50% opacity
    (60, 24, 218, 0.8*255)     #kind of purple
], dtype=rgba_dtype)

print(colors['blue'])   #all values of blues channels
print(colors[2])      #third color rgba

[  0   0 255   0 218]
(0, 0, 255, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
m1 = np.arange(15).reshape(5,3)
m2 = np.arange(6).reshape(3,2)

print(np.matmul(m1,m2))
print(m1@m2)


[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
arr = np.array([2,3,7,5,6,10,13])

#we have to inclusively negate all the elements between 3 and 8
for index,value in np.ndenumerate(arr):
  if 3<value<8:
    arr[index[0]] = np.negative(value)

print(arr)


[ 2  3 -7 -5 -6 10 13]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

-1 + 1 + 2 + 3 + 4 = 9


In [13]:
print(sum(range(5),-1))       #inbuild python sum staring from -1
from numpy import *
print(sum(range(5),-1))        #numpy sum with axis = -1 result in no axis so it sums all values


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [13]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(arr**arr)
print(arr/1/1)
print(arr<arr)
print(2<<arr)   #bitwise left shift


[   1    4   27  256 3125]
[1. 2. 3. 4. 5.]
[False False False False False]
[ 4  8 16 32 64]


NameError: name 'j' is not defined

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-15-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-15-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-15-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [16]:
arr = np.random.randn(3,3)
print(arr)
print(np.round(arr,2))

[[-5.30167730e-01  4.54595048e-01 -8.02642115e-02]
 [ 1.51617658e+00 -6.06123366e-01  6.11820227e-04]
 [-4.56014561e-01 -2.12095796e+00 -6.15555690e-01]]
[[-0.53  0.45 -0.08]
 [ 1.52 -0.61  0.  ]
 [-0.46 -2.12 -0.62]]


#### 30. How to find common values between two arrays? (★☆☆)

In [17]:


arr1 = np.array([1,2,3,4,5,6,7,8])
arr2 = np.array([1,3,5,7])

for value in np.nditer(arr1):
    if value in arr2:
        print(value,end=" ")



1 3 5 7 

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [18]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-18-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [19]:
import datetime as dt

today = dt.datetime.today()
yesterday = today - dt.timedelta(days=1)
tomorrow = today + dt.timedelta(days=1)

print(today.strftime('%d/%m/%Y'))
print(yesterday.strftime('%d/%m/%Y'))
print(tomorrow.strftime('%d/%m/%Y'))

08/06/2024
07/06/2024
09/06/2024


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [20]:
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

july_dates = np.arange(start_date, end_date, dtype='datetime64[D]')

print(july_dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [1]:
arr = np.random.uniform(-100,100,size=(5,5))
# print(arr)
integerpart = []
for value in np.nditer(arr):
    if int(value)>0:
        integerpart.append(int(value))

print(integerpart)

print((np.floor(arr)))

print(np.trunc(arr))

NameError: name 'np' is not defined

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [4]:
import numpy as np
sample = np.array([0,1,2,3,4])

arr = np.zeros(shape=(5,1),dtype=np.int8)
print(sample+arr)

# rows , col , axix
print(np.mgrid[0:5,0:5][1])

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [5]:
def generator(n):
    arr = np.random.randint(-100,100,size=(n))
    return arr
print(generator(10))

[-65 -86 -17  80  54  80  55 -38 -83   3]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
#12 values equally spaces and then indexing for exluding first and last elements
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
arr = np.random.rand(10)*100
print(np.sort(arr))

[ 2.8837693  22.78074973 25.20513119 28.87864141 31.36827732 34.55353198
 55.88543679 75.72041415 83.38176658 91.96481603]


Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [2]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(sum(my_array))
total_sum = np.add.reduce(my_array)
print(total_sum)


15
15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [5]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])

print(arr1.__eq__(arr2))
print(np.equal(arr1,arr2))
#match dimensions
print(arr1.shape==arr2.shape)

[ True  True  True  True  True]
[ True  True  True  True  True]
True


#### 43. Make an array immutable (read-only) (★★☆)

In [6]:
arr = np.array((1,2,3,4,5))
print(arr)
arr.flags.writeable = False
arr[1] = 4
print(arr)

[1 2 3 4 5]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
arr = np.random.rand(10)*100
print(arr)
print(f"max values is {arr.max()}")
index = np.where(arr == arr.max())[0]
print(f"max values is at{index[0]}")
arr[index] = 0
print(arr)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [7]:
# np.iinfo for integer and np.finfo for float
print(np.iinfo(np.int8).max)
print(np.iinfo(np.int8).min)

print(np.finfo(np.float16).max)
print(np.finfo(np.float16).min)

127
-128
65500.0
-65500.0


#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [8]:
arr = np.arange(10).reshape(10)
value =  5.6
#index of minimum differ value
idx = (np.abs(arr-value)).argmin()

print(arr[idx])


6


Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [2]:
import numpy as np
arr = np.random.rand(3,3).astype(np.float32)
print(arr.dtype)
arr = arr.astype(np.int32,copy=False)
print(arr)

float32
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
#read from text.txt
data = np.genfromtxt("D:\\codes\\python\\numpy\\text.txt",delimiter=',',dtype=np.int8,filling_values=0)
print(data)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
#np.ndenumerate(array)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [3]:
main = np.arange(10,20).reshape(10)
sample = np.array([1,2,3,4,5])

#random index for sample array elements
indices = np.random.choice(main.size,sample.size,replace=False)
print(indices)

#replacing sample values as random index
for idx,value in zip(np.nditer(indices),np.nditer(sample)):
    main[idx] = value

print(main)

[4 3 0 2 7]
[ 3 11  4  2  1 15 16  5 18 19]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [4]:

mat = np.arange(20).reshape(4,5)
print(mat)
#row wise sum horizontal 1
rowsum = mat.sum(1)
print(rowsum)
#mean of rows
rowmean = rowsum/(mat.shape[1])

#reshaping then transposing into 4*1
rowmean = np.reshape(rowmean,(1,4)).T
#print(rowmean.shape)

#subract mean of each row
print(mat-rowmean)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[10 35 60 85]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [7]:
arr = np.array([[1, 0, 3, 0],
                [0, 0, 0, 0],
                [5, 0, 0, 0]])
#row by row sum hence vertical
colsum = arr.sum(axis=0)
print(colsum)

print("folowing nth columns are null :-")
for idx,sum in enumerate(colsum):
    if sum == 0:
        print(idx,end=",")

[6 0 3 0]
folowing nth columns are null :-
1,3,

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [ ]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100